### PR TITLE
Python 3 compat

### PR DESCRIPTION
**Pull request by Psychokiller1888**
Adding python 3 compatibility tag, as it wouldn't install on octoprint 1.4.0 rc on python 3 (python 2 is EOL)

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Well, there seems to be more to be done, the plugin doesn't work at all on gpio pin, the entire KnockoutJS logic seems inverted?  let choose gpio switch mode? That would mean you can only choose GPIO if you actually don't have gpio?

**Comment by kantlivelong** [comment]
Not seeing the issue here w/ python 2.7 or 3.6 in a venv w/o GPIO. Also seems fine on 2.7 with GPIO. 

Mind retesting https://github.com/kantlivelong/OctoPrint-PSUControl/tree/py2_3_compat on py3 w/ GPIO?

**Comment by Psychokiller1888** [comment]
Yep, will do asap! Just having all 3 printers printing atm, will take a little while, but thanks for the answer!

**Comment by Psychokiller1888** [comment]
@kantlivelong Ok, I confirm your version as working on a pi 3b+, python 3.7 under buster, suing gpio to toggle a relay

**Comment by kantlivelong** [comment]
Merged . Thanks :+1:

**Pull request closed without merging**
