### PR TITLE
Change the icon to the new Font Awesome 5.0

### PR DESCRIPTION
**Pull request by LazeMSS**
Added and option to choose between the bolt and power icon

Thank you for your interest into contributing to OctoPrint-PSUControl, it's highly appreciated!

Before submitting please make sure you have ticked all points on this checklist:

  * [x] Your PR targets the devel branch.
  * [x] Your PR was opened from a custom branch on your repository (no PRs from your version of master or devel please)
  * [x] Your PR only contains relevant changes: no unrelated files, no dead code, ideally only one commit - rebase your PR if necessary!
  * [x] Your changes follow the existing coding style.
  * [x] You have tested your changes (please state how!)

Feel free to delete all this help text, then describe your PR further. You may use the template provided below to do that. The more details the better!

---

#### What does this PR do and why is it necessary?
I basically just change the icon to use the new font awesome font set - and moved the colors into the styleset (muted and text-success) to make it easier for skinning later on.
Also added an option for switching between the bolt and power icon

#### How was it tested? How can it be tested by the reviewer?
I have tested it :)

#### Further notes
I have changed newlines to unix.

### CODE REVIEW

**Comment by LazeMSS** [comment]
https://github.com/kantlivelong/OctoPrint-PSUControl/pull/156/files?diff=unified&w=1

**Comment by kantlivelong** [comment]
Perhaps I am missing something but isn't the power-off icon only part of FA Pro? Additionally the power icon is already used by the system menu.

Is simply replacing `icon-bolt` with `fas fa-bolt` not sufficient to support FA5 still be compatible with older versions?

**Comment by LazeMSS** [comment]
No the icon is free: https://fontawesome.com/icons?d=gallery&q=bolt&m=free

Yes you could just change the icon selection etc. - i agree the power icon conflicts with the other icon.

The primary was using the new icon style and the color "styles" 👍

**Comment by kantlivelong** [comment]
Hey @LazeMSS,

As discussed on chat, going to reject this for now since I want to keep compat w/ older OctoPrint versions until Py2 support is dropped.

**Pull request closed without merging**
