### PR TITLE
Add autoconnect to printer after power on

### PR DESCRIPTION
**Pull request by chriswal**
Thank you for your interest into contributing to OctoPrint-PSUControl, it's highly appreciated!

Before submitting please make sure you have ticked all points on this checklist:

  * [ ] Your PR targets the devel branch.
  * [ ] Your PR was opened from a custom branch on your repository (no PRs from your version of master or devel please)
  * [ ] Your PR only contains relevant changes: no unrelated files, no dead code, ideally only one commit - rebase your PR if necessary!
  * [ ] Your changes follow the existing coding style.
  * [ ] You have tested your changes (please state how!)

Feel free to delete all this help text, then describe your PR further. You may use the template provided below to do that. The more details the better!

---

#### What does this PR do and why is it necessary?
If your printer controller is not powered when the power supply is off, the printer is offline when power returns. you can automatically connect the printer after power on.

#### How was it tested? How can it be tested by the reviewer?
power octoprint on ...turn off printer ... turn on printer
i tested with system commands and an ethernet controllable switch

#### Any background context you want to provide?
octoprint tends to change the usb port when powering off and on the printer
if it changed it you get a communication error .. to prevent that add /dev/serial/by-id/...... device definition to the port parameter

#### Screenshots (if appropriate)
2018-03-27 00_24_04-octoprint

### CODE REVIEW

**Comment by kantlivelong** [comment]
Hi @chriswal 

Thanks for the PR. I've gotten a request a few times now and each time I refer them to [PortLister](https://plugins.octoprint.org/plugins/portlister/). Can you tell me what this does that PortLister doesn't?

**Comment by chriswal** [comment]
i don't know portlister ..would have used it for the manual approach.
but for the automatic approach i would prefer to connect after i powered on directly.
i only call the _printer.connect() the other changes are only for the gui

you are already using _printer.disconnect() (disconnect after power off)

i only wanted to share my changes ..so no need for you to implement it if you dont like it ,-)
i will use it that way.

**Comment by kantlivelong** [comment]
PortLister will essentially watch for USB serial devices and autoconnect if already disconnected. I suppose that wouldn't cover plain old serial or TCP. Ideally if this were to be implemented it would need to cover all 3 scenarios. USB serial makes it a little bit harder because the device path (or COM port) could change.

**Comment by chriswal** [comment]
can octoprint use the plain serial or tcp connection?
if so you can enter the port into the parameter field and it should be working ...

**Comment by Martyfree123** [comment]
This would be an amazing feature because Portlister doesn't work on my LulzBot TAZ 5

**Comment by AABatteries** [comment]
Yes this merge would be great - and would make PSU Control a complete package that covers every possible need for such a controller. What's your final decision on this @kantlivelong ?

**Comment by saschaludwig** [comment]
+1, please merge

**Comment by wezzix** [comment]
@chriswal Since PortLister currently doesn't auto connect and since this pull request does not get accepted into PSU Control, would you care to publish it as a new plugin "PSU Control with Auto Connect"? This is faster than PortLister since it doesn't have the polling lag. I'm using your fork and it's really working well, and I'm sure others would find it very useful as well.

**Comment by chriswal** [comment]
@wezzix as i had problems with the turn off feature with g-codes ..i have to debug it first.

**Comment by RNRMentor** [comment]
@kantlivelong I super appreciate the work that you have done on PSU Control plugin.  That said, you are ignoring so many users whose have issue with PortLister not connecting automatically.  Could you please implement a solution?

**Comment by kantlivelong** [comment]
@RNRMentor, I've kept this PR open in the event that it made sense to have such a feature in PSUControl. However, after thinking about it for a while I still stand by my belief that this type of feature should really be a PR for PortLister or as it's own separate plugin so that anyone can benefit from the functionality, not just PSUControl users. 

That said, if I were to implement such a feature as another plugin or a PR to PortLister I would have it poll available serial ports whether built-in, USB, or even TCP to establish a socat session.

**Pull request closed without merging**
