### PR TITLE
Invert sense

### LINKED ISSUE #36: Invert sense pin
I hooked up my PSU sense with an optocoupler, but this has a side effect of inverting the logic for the pin. It would be handy if there was an "Invert" checkbox for the sense pin.  I hooked it up using the internal pullup of the rpi GPIO,

### PR DESCRIPTION
**Pull request by agreen**
Closes #36

### CODE REVIEW

**Comment by agreen** [comment]
Just checking in on this, if you have any questions/issues.

**Comment by kantlivelong** [comment]
Haven't had a chance to test this yet. One thing I noticed that could be changed is the senseGPIOPinPUD drop down in the settings UI. I think it would be nicer to put it horizontally before or after the invert checkbox with no label. Change "Off" to "No Pull Up/Down" or something similar. 

Thoughts?

**Comment by agreen** [comment]
I was concerned with the length of the drop down. I originally had it something along those lines. I figured the page was better suited to vertical than horizontal, but I'm up for anything. Let me know if you want me to modify the PR.

**Comment by kantlivelong** [comment]
As long as it sits in one line it should be fine.

Thanks for the help!

**Comment by kantlivelong** [comment]
Alright I've finally tested the code changes. Looks good! :thumbsup:

If you prefer I can make the UI changes. Let me know.

**Comment by agreen** [comment]
Might be faster if you do, I've run into a few setbacks on my side.  Glad you like it, and thank you for all the work you've put into the plugin.

**Comment by kantlivelong** [comment]
Alright. Added to my TODO list.

Thanks for your additions!

**Comment by kantlivelong** [comment]
Merged

**Pull request closed without merging**
